-- =====================================================
-- DATABASE SISTEM PERSEDIAAN FLORIST
-- PostgreSQL / Supabase
-- =====================================================

-- Menghapus tabel jika sebelumnya sudah ada
DROP TABLE IF EXISTS detail_transaksi CASCADE;
DROP TABLE IF EXISTS transaksi CASCADE;
DROP TABLE IF EXISTS produk CASCADE;
DROP TABLE IF EXISTS supplier CASCADE;


-- =====================================================
-- 1. TABEL SUPPLIER
-- =====================================================

CREATE TABLE supplier (
    supplier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_supplier VARCHAR(100) NOT NULL,
    telepon VARCHAR(20),
    alamat TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- =====================================================
-- 2. TABEL PRODUK
-- =====================================================

CREATE TABLE produk (
    produk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT REFERENCES supplier(supplier_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    nama_produk VARCHAR(100) NOT NULL,
    kategori VARCHAR(50) NOT NULL,
    satuan VARCHAR(30) NOT NULL DEFAULT 'pcs',

    harga_beli NUMERIC(15,2) NOT NULL DEFAULT 0,
    harga_jual NUMERIC(15,2) NOT NULL DEFAULT 0,

    stok INTEGER NOT NULL DEFAULT 0,
    stok_minimum INTEGER NOT NULL DEFAULT 5,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT harga_beli_tidak_negatif
        CHECK (harga_beli >= 0),

    CONSTRAINT harga_jual_tidak_negatif
        CHECK (harga_jual >= 0),

    CONSTRAINT stok_tidak_negatif
        CHECK (stok >= 0),

    CONSTRAINT stok_minimum_tidak_negatif
        CHECK (stok_minimum >= 0)
);


-- =====================================================
-- 3. TABEL TRANSAKSI
-- =====================================================

CREATE TABLE transaksi (
    transaksi_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nomor_transaksi VARCHAR(30) UNIQUE NOT NULL,

    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,

    jenis_transaksi VARCHAR(10) NOT NULL,

    total NUMERIC(15,2) NOT NULL DEFAULT 0,

    keterangan TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT jenis_transaksi_valid
        CHECK (jenis_transaksi IN ('MASUK', 'KELUAR')),

    CONSTRAINT total_tidak_negatif
        CHECK (total >= 0)
);


-- =====================================================
-- 4. TABEL DETAIL TRANSAKSI
-- =====================================================

CREATE TABLE detail_transaksi (
    detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    transaksi_id BIGINT NOT NULL
        REFERENCES transaksi(transaksi_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    produk_id BIGINT NOT NULL
        REFERENCES produk(produk_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    jumlah INTEGER NOT NULL,

    harga NUMERIC(15,2) NOT NULL,

    subtotal NUMERIC(15,2)
        GENERATED ALWAYS AS (jumlah * harga) STORED,

    CONSTRAINT jumlah_harus_positif
        CHECK (jumlah > 0),

    CONSTRAINT harga_detail_tidak_negatif
        CHECK (harga >= 0)
);


-- =====================================================
-- INDEX
-- =====================================================

CREATE INDEX idx_produk_supplier
ON produk(supplier_id);

CREATE INDEX idx_transaksi_tanggal
ON transaksi(tanggal);

CREATE INDEX idx_transaksi_jenis
ON transaksi(jenis_transaksi);

CREATE INDEX idx_detail_transaksi
ON detail_transaksi(transaksi_id);

CREATE INDEX idx_detail_produk
ON detail_transaksi(produk_id);


-- =====================================================
-- DATA AWAL SUPPLIER
-- =====================================================

INSERT INTO supplier
(nama_supplier, telepon, alamat)
VALUES
('Bunga Indah Florist Supplier', '081234567890', 'Semarang'),
('Flora Nusantara', '082345678901', 'Solo'),
('Mawar Jaya', '083456789012', 'Yogyakarta'),
('Sumber Bunga Sejahtera', '084567890123', 'Salatiga');


-- =====================================================
-- DATA AWAL PRODUK
-- =====================================================

INSERT INTO produk
(supplier_id, nama_produk, kategori, satuan,
 harga_beli, harga_jual, stok, stok_minimum)
VALUES
(1, 'Mawar Merah', 'Bunga Potong', 'tangkai',
 15000, 25000, 20, 5),

(1, 'Mawar Putih', 'Bunga Potong', 'tangkai',
 15000, 25000, 15, 5),

(2, 'Lily Putih', 'Bunga Potong', 'tangkai',
 20000, 30000, 12, 5),

(2, 'Baby Breath', 'Bunga Potong', 'ikat',
 12000, 20000, 10, 3),

(3, 'Tulip', 'Bunga Potong', 'tangkai',
 18000, 30000, 8, 3),

(4, 'Vas Kaca', 'Aksesoris', 'pcs',
 25000, 40000, 7, 2),

(4, 'Pita Satin', 'Aksesoris', 'roll',
 10000, 18000, 15, 3),

(1, 'Kertas Buket', 'Kemasan', 'lembar',
 5000, 10000, 25, 5);


-- =====================================================
-- ROW LEVEL SECURITY
-- =====================================================

ALTER TABLE supplier ENABLE ROW LEVEL SECURITY;
ALTER TABLE produk ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaksi ENABLE ROW LEVEL SECURITY;
ALTER TABLE detail_transaksi ENABLE ROW LEVEL SECURITY;


-- =====================================================
-- POLICY SUPPLIER
-- =====================================================

CREATE POLICY "supplier_select"
ON supplier
FOR SELECT
TO anon
USING (true);

CREATE POLICY "supplier_insert"
ON supplier
FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY "supplier_update"
ON supplier
FOR UPDATE
TO anon
USING (true)
WITH CHECK (true);

CREATE POLICY "supplier_delete"
ON supplier
FOR DELETE
TO anon
USING (true);


-- =====================================================
-- POLICY PRODUK
-- =====================================================

CREATE POLICY "produk_select"
ON produk
FOR SELECT
TO anon
USING (true);

CREATE POLICY "produk_insert"
ON produk
FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY "produk_update"
ON produk
FOR UPDATE
TO anon
USING (true)
WITH CHECK (true);

CREATE POLICY "produk_delete"
ON produk
FOR DELETE
TO anon
USING (true);


-- =====================================================
-- POLICY TRANSAKSI
-- =====================================================

CREATE POLICY "transaksi_select"
ON transaksi
FOR SELECT
TO anon
USING (true);

CREATE POLICY "transaksi_insert"
ON transaksi
FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY "transaksi_update"
ON transaksi
FOR UPDATE
TO anon
USING (true)
WITH CHECK (true);

CREATE POLICY "transaksi_delete"
ON transaksi
FOR DELETE
TO anon
USING (true);


-- =====================================================
-- POLICY DETAIL TRANSAKSI
-- =====================================================

CREATE POLICY "detail_select"
ON detail_transaksi
FOR SELECT
TO anon
USING (true);

CREATE POLICY "detail_insert"
ON detail_transaksi
FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY "detail_update"
ON detail_transaksi
FOR UPDATE
TO anon
USING (true)
WITH CHECK (true);

CREATE POLICY "detail_delete"
ON detail_transaksi
FOR DELETE
TO anon
USING (true);


-- =====================================================
-- SELESAI
-- =====================================================

SELECT 'Database Sistem Persediaan Florist berhasil dibuat!'
AS status;